// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjirldvzgnuitggmfons.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaXJsZHZ6Z251aXRnZ21mb25zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2MTY0OTgsImV4cCI6MjA2NTE5MjQ5OH0.aHcOuyaI1Z0-0wr37kS9mzuFD2h2N5fz5Q8OYR8up0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);